layout_spectrum: 0.9459567272569984
typography_spectrum: 0.6767920255661011
color:
  brandStrength: 0.7538384068757296
  lightness: 0.7403074505273253
  saturation: 0.7336384288500994
  rhythmicContrast: 0.5042355391196907
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
author:
  name: Made by AREEVOL
  email: vladimircavalcante@mac.com
  url: 'https://www.facebook.com/vladimir.cavalcante'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/728fe2a2-f5c7-417e-8503-bf4bd2254468.jpg
name: Mosaico Esportivo - Apaixonados por Esporte
navigation:
  - name: OS SEM BANDEIRAS
    id: c721e5ec-42bf-47fe-89cd-4cf6a0a106b0
    type: content
  - name: ÃGUA SAGRADA OU CRISTAL?
    id: d95469db-3b10-4189-addb-fc63284a8884
    type: content
  - name: Mosaico no FACEBOOK
    url: 'https://www.facebook.com/mosaicoesportivo/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a7ba94d-0ea2-4b22-a275-378fcef53848.jpg
title: ''
