layout_spectrum: 0.2321643226314336
typography_spectrum: 0.04707723576575518
color:
  brandStrength: 0.796645495807752
  lightness: 0.26733853155747056
  saturation: 0.250907234614715
  rhythmicContrast: 0.8053976595401764
  brandColors:
    - '#12180E'
    - '#478F9E'
    - '#667635'
    - '#73B3BD'
    - '#A7EAF0'
author:
  name: Made by AREEVOL
  email: vladimircavalcante@mac.com
  url: 'https://www.facebook.com/vladimir.cavalcante'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/728fe2a2-f5c7-417e-8503-bf4bd2254468.jpg
name: Mosaico Esportivo - Apaixonados por Esporte
navigation:
  - name: OS SEM BANDEIRAS
    id: c721e5ec-42bf-47fe-89cd-4cf6a0a106b0
    type: content
  - name: ÃGUA SAGRADA OU CRISTAL?
    id: d95469db-3b10-4189-addb-fc63284a8884
    type: content
  - name: Mosaico no FACEBOOK
    url: 'https://www.facebook.com/mosaicoesportivo/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a7ba94d-0ea2-4b22-a275-378fcef53848.jpg
title: ''
